### ISSUE TITLE
v0 version

### ISSUE THREAD

**Issue by funderburkjim** [funderburkjim/kosha-dev#1]
@drdhaval2785 

First version of kosha dictionaries ready for your perusal.

Follow instructions of v0 readme to install the v0 app and then
try out the displays.

There are numerous areas which will need further adjustments.
I suggest you focus on getting make_xml.py, basicadjust.php, and basicdisplay.php to your satisfaction.
You could do this either by editing the v0 versions of these files.
Or making a new v1 (as copy of v0) and then modifying v1.

When the xml and displays are deemed satisfactory,  we can consider the further adjustments.

Just for reference,  this is related to https://github.com/sanskrit-lexicon/COLOGNE/issues/408 and 405, 406 issues.

**Comment by funderburkjim** [comment]
The url https://sanskrit-lexicon.uni-koeln.de/work/kosha-dev/v0/apps/harsa/web/.
may let @gasyoun, @andhrabharati and other interested persons follow the discussion.

**Comment by funderburkjim** [comment]
Sample inputs are ka, jala.

Basic and mobile1 displays work fine.  Advanced search and listdisplay sort of work, but with some problems.
Once you get a display for one word, you can also get display for the other words or meaning words.

No scanned images are available yet, and the displays are based on a sample of about 100 verses.

**Comment by gasyoun** [comment]
> No scanned images are available yet, and the displays are based on a sample of about 100 verses.

Can we add spaces? `sarpa,gaja,śīrṣa` --> `sarpa, gaja, śīrṣa`

![ddsdfsfdsd](https://user-images.githubusercontent.com/80761/227053289-b6246c42-622c-4c93-b842-df73d3bf9502.jpg)

**Comment by funderburkjim** [comment]
Space added after comma in meanings:

<img width="694" alt="image" src="https://user-images.githubusercontent.com/6393033/228027427-a58ba4d9-53ac-45f4-bf93-7e553f673f6e.png">

**Comment by funderburkjim** [comment]
Note this change made in v1 only.
