### ISSUE TITLE
Discussion of v2

### ISSUE THREAD

**Issue by funderburkjim** [funderburkjim/kosha-dev#10]
In v2, @drdhaval2785  made an additional 'harsa1.xml' (and provided an invertible conversion between harsa.xml and harsa1.xml).

Request him to discuss
* the structure of 'harsa1.xml', when compared to 'harsa.xml'
* The purpose of harsa1.xml  (it is not used in the v2 displays).
* Also request a brief intro to v2 in kosha-dev/README.md

**Comment by drdhaval2785** [comment]
I think there is not much to be documented there. It is a compressed version of harsa.xml. Currently I am not sure of the use cases as of now. Therefore, not pursuing it any further. The v1 works just fine for me.

@funderburkjim , Kindly add Anekarthanamamala of Harshakirti in CDSL. 
csl-orig and other places.
