### ISSUE TITLE
version v3

### ISSUE THREAD

**Issue by funderburkjim** [funderburkjim/kosha-dev#11]
Change dictionary abbreviation name to 'ANHK',
  per request at https://github.com/sanskrit-lexicon/COLOGNE/issues/405

As with version 2, there are two versions of the xml form:  
* anhk.xml to be used in CDSL displays
  * anhk.dtd will be the dtd for anhk.xml
* anhk1.xml an equivalent but form that Dhaval finds useful
  * anhk1.dtd will be the dtd for anhk1.xml.

**Comment by funderburkjim** [comment]
<img width="913" alt="image" src="https://user-images.githubusercontent.com/6393033/231264937-f580cc19-c442-486c-b10e-4ea9053b43c5.png">

**Comment by drdhaval2785** [comment]
Dear @funderburkjim 
When will this dev version go to the live CDSL website, along with appropriate changes in csl-homepage too?
