### ISSUE TITLE
abch: missing 1st line of verse 39

### ISSUE THREAD

**Issue by funderburkjim** [funderburkjim/kosha-dev#13]
```
<L>12<pc>5
<eid>17<syns>arhanmAtf-strI,marudevA-strI,vijayA-strI,senA-strI,sidDArTA-strI,maNgalA-strI,susImA-strI,pfTvI-strI,lakzmaRA-strI,rAmA-strI,nandA-strI,vizRu-strI,jayA-strI,SyAmA-strI,suyaSA-strI,suvratA-strI,acirA-strI,SrI-strI,devI-strI,praBAvatI-strI,padmA-strI,vaprA-strI,SivA-strI,vAmA-strI,triSalA-strI
;; marudevA grandmother of arhat fzaBa
;; vijayA mother of 2nd Arhat
;; lakzmaRA  mother of 8th arhat;
;; MISSING first line of verse 39.
;;   मरुदेवा विजया सेना सिद्डार्था अ मङला .    <<< insert
tataH susImA pfTvI lakzmaRA rAmA tataH param .. 39 ..
nandA vizRurjayA SyAmA suyaSAH suvratAcirA .
SrIrdevI praBAvatI ca padmA vaprA SivA taTA .. 40 ..
vAmA triSalA kramataH pitaro mAtaro'rhatAm .
<LEND>
```
Looks like the line shown needs to be inserted.. @drdhaval2785 Agree?

**Comment by drdhaval2785** [comment]
I completely agree with you.
In fact, this correction was made in my file.
Attaching the new file with some minor corrections.
You may use this revised file.
[abch1.txt](https://github.com/funderburkjim/kosha-dev/files/11447973/abch1.txt)

**Comment by funderburkjim** [comment]
## spelling error.


using revised abch1 of previous comment.

At line 901 (verse 169),  
```
तिर्यग्दिशां तु पतय इन्द्राग्नियमर्नैर्ॠताः ।    <<< PROBLEM 
          SOLUTION: इन्द्राग्नियमनैरॄताः   OR  इन्द्राग्नियमनैरृताः
वरुणो वायुकुबेरावीशानश्च यथाक्रमम् ॥ १६९ ॥
```
<img width="746" alt="image" src="https://github.com/funderburkjim/kosha-dev/assets/6393033/bad109b2-43b9-4a97-9a47-928a169b7433">


Note:  This was noticed in conversion of abch1 (devanagari) to abch (slp1).
   In the round trip, there are a small number of discrepancies.  related to 
   semi-vowel 'r' followed by vowels 'f' or 'F' (SLP1).  This is probably a side-issue
   of transcoding.  It was just an accident that this discrepancy surfaced the problem.

@drdhaval2785 will leave the revision to abch1 to you.

**Comment by funderburkjim** [comment]
## two changes
See the commit 317d1a5
1. इन्द्राग्नियमनैरृताः  (mentioned above)
2. Insert missing `<LEND>`

**Comment by drdhaval2785** [comment]
Great
