### ISSUE TITLE
non-synonyms (manda)

### ISSUE THREAD

**Issue by funderburkjim** [funderburkjim/kosha-dev#15]
Continue discussion regarding [This part of issue 12](https://github.com/funderburkjim/kosha-dev/issues/12#issuecomment-1543288356)

**Comment by funderburkjim** [comment]
## compare L=1531 to L=2
```
<L>1531<pc>47
<eid>3089<syns>Badra-puM
<eid>3090<syns>manda-puM
<eid>3091<syns>mfga-puM
<eid>3092<syns>miSra-puM
<eid>3093<syns>gajajAti-strI
Badro manda mfgo miSraScatasro gajajAtayaH .. 1218 ..
<LEND>

;; List of 24 arhats, from fzaBa ... vIra (= mahAvIra)
<L>2<pc>5
<eid>2<syns>fzaBa-puM,ajita-puM,SamBava-puM,aBinandana-puM,sumati-puM,padmapraBa-puM,supArSva-puM,candrapraBa-puM,suviDi-puM,SItala-puM,SreyAMsa-puM,vAsupUjya-puM,vimala-puM,anantatIrTakft-puM,Darma-puM,SAnti-puM,kunTu-puM,ara-puM,malli-puM,munisuvrata-puM,nami-puM,nemi-puM,pArSva-puM,vIra-puM
etasyAmavasarpiRyAmfzaBo'jitaSaMBavO .
aBinandanaH sumatistataH padmapraBABiDaH .. 26 ..
supArSvaScandrapraBaSca suviDiScATa SItalaH .
SreyAMso vAsupUjyaSca vimalo'nantatIrTakft .. 27 ..
DarmaH SAntiH kuMTuraro malliSca munisuvrataH .
namirnemiH pArSvo vIraScaturviMSatirarhatAm .. 28 ..
<LEND>
```

In both cases, we have a list of words that are not synonyms.
* The Badra list  (Badra - miSra) are kinds or qualities of elephants
  * gajajAti  ('elephant-kind') gives a name to the Badra list
* The fzaBa list provides names for the 24 arhats (of present era).

I would expect L=2 and L=1531 to be coded similarly.
e.g.
```
<L>1531<pc>47
<eid>3089<syns>Badra-puM,manda-puM,mfga-puM,miSra-puM
<eid>3093<syns>gajajAti-strI
Badro manda mfgo miSraScatasro gajajAtayaH .. 1218 ..
<LEND>
```

Also, possibly in L=2 there should also be the class name arhan,  
```
<L>2<pc>5
<eid>2<syns>fzaBa-puM,ajita-puM,SamBava-puM,aBinandana-puM,sumati-puM,padmapraBa-puM,supArSva-puM,candrapraBa-puM,suviDi-puM,SItala-puM,SreyAMsa-puM,vAsupUjya-puM,vimala-puM,anantatIrTakft-puM,Darma-puM,SAnti-puM,kunTu-puM,ara-puM,malli-puM,munisuvrata-puM,nami-puM,nemi-puM,pArSva-puM,vIra-puM
<eid>2a<syns>arhan
...
<LEND>
```

**Comment by funderburkjim** [comment]
## a parameter for syns?

The displays show the phrase 'synonymns:' 
<img width="582" alt="image" src="https://github.com/funderburkjim/kosha-dev/assets/6393033/9f2e8f80-f50e-485d-989d-3b448c902d32">

We know that 'synonymns:' is not descriptive in some cases,, such as L=2 and L=1531 above.
* We could just remove 'synonymns:' phrase and show NO phrase for the `<syns>` tag.
* We could add a parameter  to `<syns>` tag and show a phrase based on the value of that parameter. e.g. 
  * `<syns>` with no parameter would show 'synonyms:' (as now)
   * `<syns n="x">` would show 'x:'  

The second approach would be more informative, but would require modification of abch1.txt:
* deciding which lists should have a parameter (non-synonyms)
* and what values that parameter should take for the non-synonyms lists.

**Comment by drdhaval2785** [comment]
@funderburkjim,
I am glad that this issue came up. It is a question regarding semantic relationships between synsets.
https://sanskrit.uohyd.ac.in/scl/amarakosha/amarakosha_knowledge_structure.pdf is a great resource. 
pages 32-34
Pages 53-61
Pages 95-100

**Comment by drdhaval2785** [comment]
We may require to implement some further markups to accurately describe the relationships between two synsets.

**Comment by drdhaval2785** [comment]
There is technically no need for a synset to have two headwords. In most of the WordNets around the world, a synset is {headwordlist, meaning} set. Headwordlist is a list of headwords. May have only one headword.

**Comment by drdhaval2785** [comment]
I agree that L=2 needs to be encoded as 1531. I will need to decide the appropriate tags other than “syns”. Will need to document with help of the abovementioned thesis.

**Comment by drdhaval2785** [comment]
Now these items are treated separately. Issue does not survive now.
