### ISSUE TITLE
abchheader.xml

### ISSUE THREAD

**Issue by funderburkjim** [funderburkjim/kosha-dev#17]
abchheader.xml  will be needed for the CDSL version.

Many of the required details may be taken from the METADATA portion of [abch1.txt](https://github.com/funderburkjim/kosha-dev/blob/main/v4/prep/abch/abch1.txt).

@drdhaval2785   This is for you to do, agree?

**Comment by funderburkjim** [comment]
Also the 'WorldCat reference' and 'Bibliographic entry' , it these are possible to determine. 
Again @drdhaval2785  should do;  @gasyoun may know how to get these, as he provided these for all (or most) of the CDSL dictionaries.

**Comment by drdhaval2785** [comment]
I will do this, @funderburkjim .

**Comment by drdhaval2785** [comment]
Added initial commit of abchheader.xml at https://github.com/funderburkjim/kosha-dev/blob/main/v4/csl-orig/abch/abchheader.xml

**Comment by drdhaval2785** [comment]
Worldcat reference - https://www.worldcat.org/title/163083433

Bibliographic details (in Chicago  format)
```
Hemachandra Hemachandra. 1896. The Abhidhâna-Chintâmạṇi the Abhidhâna-Chintâmaṇi-Pariśishta the Anekârtha-Sangraha the Nighaṇtu-Sésha and the Lingânuśâsana. Bombay: Nirṇaya-Sâgara Press.
```

I don't know whether and where to put them in abchheader.xml file.

**Comment by drdhaval2785** [comment]
@funderburkjim 
Completed this task.
You may close if you feel OK.

**Comment by funderburkjim** [comment]
Worldcat and Bibliographic details don't go in abchheader.xml, but in 
https://github.com/funderburkjim/kosha-dev/blob/main/v4/csl-websanlexicon/makotemplates/web/index.php.

I'll put them in per your details.

**Comment by drdhaval2785** [comment]
Time to put worldcat reference @funderburkjim ?

**Comment by funderburkjim** [comment]
The worldcat link is present for ABCH:
```
<li><a href="https://www.worldcat.org/title/Abhidhānacintāmaṇi of Hemacandrācārya">WorldCat reference</a></li>
```
but this url does not work -- Get an 'Oops something went wrong' page from worldcat.

So you need to somehow find the right link for ABCH at worldcat.org.

**Comment by drdhaval2785** [comment]
Will find one and close this issue

**Comment by drdhaval2785** [comment]
https://search.worldcat.org/title/163083433

This is the correct worldcat location

**Comment by drdhaval2785** [comment]
This worldcat entry added in all three dictionaries ABCH, ACPH and ACSJ.
