### ISSUE TITLE
abch Display complete verses

### ISSUE THREAD

**Issue by funderburkjim** [funderburkjim/kosha-dev#18]
It has been explained ([ref](https://github.com/funderburkjim/kosha-dev/issues/12#issuecomment-1543288356)) that synsets
* may span multiple verses
* may include only one line of a particular verse

This comment makes the case for inclusion of *both verse lines* in each display.

Consider example of सूर्याश्मन् where only the first line of a verse is currently displayed.

<img width="680" alt="image" src="https://github.com/funderburkjim/kosha-dev/assets/6393033/5a356fa9-af94-4537-84bf-f85269c6bcb2">

We don't know the verse.   If a user looks at the scan of page 41,  he must scan the entire page text to find this verse (which happens
to be on the last line).

If both lines of the verse are in the display, then the user need only examine the verse numbers to find verse १०६७ in the scan.

**Comment by funderburkjim** [comment]
A solution could be accomplished in two ways:
1. modify [abch1.txt](https://github.com/funderburkjim/kosha-dev/blob/main/v4/prep/abch/abch1.txt), the 'original' form
   of the digitization
   * perhaps for 'semantic' reasons we should maintain the correspondence between synsets and corresponding verse fragments
2. provide the 'missing' verse fragments in abch.xml, via an extra step prior to (or part of) make_xml.py.

**Comment by funderburkjim** [comment]
@drdhaval2785 
a. Do you agree with this idea of *displaying* full verses?
b. If so, which 'solution' do you prefer?   (my guess is that you would prefer solution 2.).

**Comment by drdhaval2785** [comment]
I prefer solution 2.

**Comment by drdhaval2785** [comment]
Jim has implemented a script to add additional information about the verses which do not end with verse number.
Closing the issue.
