### ISSUE TITLE
Basic display observation 1

### ISSUE THREAD

**Issue by drdhaval2785** [funderburkjim/kosha-dev#2]
@funderburkjim 
It is quite nice to see the Sanskrit koshas into action, so quickly. Thank you.
I am noting the observations which I feel are important.

# Unnecessary display of other headwords

When I search for 'ka' in the basic display, the current display shows 'Sloka' and 'loka' too alongwith the searched 'ka'.
These two are unnecessary and confusing. We should remove them.

# Screenshot

![Screenshot_2023-03-19_12-40-54](https://user-images.githubusercontent.com/5755132/226159954-67042e3d-4f3c-416a-a2c7-4b0a2fb0c13c.png)

**Comment by drdhaval2785** [comment]
# Current display for search 'sUrya'

![Screenshot_2023-03-19_12-47-57](https://user-images.githubusercontent.com/5755132/226160278-31b8a9f4-424f-42f1-baf5-addd6d9912c3.png)

# Expected result
```
सूर्य [Printed book page 140]
क-पुं meaning(s) सूर्य,वेधस्

सूर्ये वेधसि वायौ कः कं सुखे मस्तके जले ।
अनुष्टुब्यशसोः श्लोको लोकस्तु भुवने जने ॥ १ ॥
[ID=1]

पतङ्ग-पुं meaning(s) पक्षिन्,सूर्य

पतङ्गौ पक्षिसूर्यौ च पूगः क्रमुकवृन्दयोः ।
सारङ्गश्चातके भृङ्गे कुञ्जरे हरिणेऽपि च ॥ ८ ॥
[ID=7]
[Printed book page 150]
इन-पुं meaning(s) स्वामिन्,सूर्य

वनं जले कानने स्याद्भुवनं विष्टपे जले ।
इनः स्वामिनि सूर्ये च जिनोऽर्हद्बुद्धविष्णुषु ॥ ५२ ॥
[ID=49]
चित्रभानु-पुं meaning(s) सूर्य,वह्नि
भानु-पुं meaning(s) सूर्य,मयूख

चित्रभानू सूर्यवह्नी भानुः सूर्यमयूखयोः ।
शिखी वह्नौ मयूरे च पत्त्रिणौ शरपक्षिणौ ॥ ५५ ॥
[ID=52]
[Printed book page 152]
हरि-पुं meaning(s) सूर्य,चन्द्र,यम,विष्णु,वासव,दर्दुर,हय,मृगेन्द्र,वानर,वायु

सूर्ये चन्द्रे यमे विष्णौ वासवे दर्दुरे हये ।
मृगेन्द्रे वानरे वायौ दशस्वपि हरिः स्मृतः ॥ ७३ ॥
[ID=70]
```

**Comment by gasyoun** [comment]
> It is quite nice to see the Sanskrit koshas into action

@drdhaval2785 was waiting for a few years, I believe. So I'm happy for him being happy.

**Comment by funderburkjim** [comment]
@drdhaval2785 
[revised make_xml.py](https://gist.github.com/funderburkjim/260065d2978ec6035385ea44754e2c47#file-make_xml-py)

This problem could be solved either at the xml level or the html level.
The above is a solution at xml level.  

I have not pushed this (or any other) change -- If you like this solution, will let you use this revised version, and push.

The differences are:
* new function get_k1
* new function get_datalines1
* revised function get_datalines. last 4 lines.

## revised xml record for ka
```
<H1><h><key1>ka</key1><key2>ka</key2></h><body>
<hwdetails>
   <hwdetail><hw><s>ka-puM</s></hw><meaning><s>sUrya,veDas</s></meaning></hwdetail>
  <hwdetail><hw><s>ka-klI</s></hw><meaning><s>suKa,mastaka,jala</s></meaning></hwdetail>
</hwdetails>
<entrydetails>
 <entrydetail><s>sUrye veDasi vAyO kaH kaM suKe mastake jale .</s></entrydetail>
 <entrydetail><s>anuzwubyaSasoH Sloko lokastu Buvane jane .. 1 ..</s></entrydetail>
</entrydetails>
</body><tail><L>1</L><pc>140</pc></tail></H1>

```
display for 'ka' with this revision.

<img width="491" alt="image" src="https://user-images.githubusercontent.com/6393033/226197888-22c58d53-4036-4e71-9abb-2ed7e91077fb.png">

The cologne display not revised.  Will sync with kosha-dev after your revision.

**Comment by drdhaval2785** [comment]
Just a brief note. I will not be able to attend to this before March end.

**Comment by funderburkjim** [comment]
Is it ok if I push this change through -- will that interfere with changes you have made?

**Comment by funderburkjim** [comment]
I am going to push this change through, as well as other changes, rather than wait until end of March.

**Comment by drdhaval2785** [comment]
The changes you pushed are unlikely to affect my work. I am working in a fork of this repository and working in v1.
