### ISSUE TITLE
Version 5.1 - display by syns (abch)

### ISSUE THREAD

**Issue by funderburkjim** [funderburkjim/kosha-dev#22]
In #20, Dhaval thought it might be helpful to list the syns by gender.
v5.1 provides one expression of this idea.
 The display programs (basicdisplay and basicadjust) were revised.

**Comment by funderburkjim** [comment]
## Sample
Compare to [v5 display](https://github.com/funderburkjim/kosha-dev/issues/20#issuecomment-1778327623).

<img width="739" alt="image" src="https://github.com/funderburkjim/kosha-dev/assets/6393033/b14fd493-0bbf-4a91-9cee-f0340001ddcf">

**Comment by funderburkjim** [comment]
Since the syn ordering will change usually from the verse (as you observed), I used alphabetical sorting for the syns (and also for the 'gender rows'.

@drdhaval2785  
* Does v5.1 get at what you were imagining?  
* Do you prefer v5.1 over v5?

**Comment by drdhaval2785** [comment]
Alphabet sorting is fine.
Yes, I prefer the gender rows i.e. v5.1 over v5.

**Comment by drdhaval2785** [comment]
One remark on the display part.

Can we have a horizontal line between `[ID=3]` and `[Printed book page 48]`?

As we have too much information on display including synonyms and gender, it will be useful visually to provide the user a Visual line break when one synset gets over and the new one starts.
Currently it seems to be in the continuation of the previous one.

**Comment by drdhaval2785** [comment]
Barring this comment, this issue is closeable for me.

**Comment by funderburkjim** [comment]
Added horizontal line.
Closing issue.
