### ISSUE TITLE
Abhidhānacintāmaṇipariśiṣṭa (ACPH) questions

### ISSUE THREAD

**Issue by drdhaval2785** [funderburkjim/kosha-dev#24]
This is a placeholder to understand where I go wrong in installation of ACPH dictionary

**Comment by drdhaval2785** [comment]
# Q1. What to change for proper display of genders

For example, when I search 'Sani' in ABCH, I get the gender block properly.

![Screenshot_2023-12-06_14-05-32](https://github.com/funderburkjim/kosha-dev/assets/5755132/fd22fcfe-144a-44bd-8475-578358de9057)

When I search for 'paNgu' in ACPH, I get it wrong. 'puM' gets merged before the word block and there is nothing in the gender / synset table block.

![Screenshot_2023-12-06_14-06-52](https://github.com/funderburkjim/kosha-dev/assets/5755132/19fd2970-67b5-4a84-ae1b-86fff60d8704)

What script should I change?

**Comment by drdhaval2785** [comment]
@funderburkjim 
Kindly do git pull so that you have my trial of ACPH based on your ABCH work.
For your info - ACPH is addenda of ABCH found in the commentary of ABCH by author himself.

**Comment by funderburkjim** [comment]
@drdhaval2785  - one minor change in getword_data.php does the trick:

<img width="562" alt="image" src="https://github.com/funderburkjim/kosha-dev/assets/6393033/3ac7a5b4-9d9e-44af-876d-6b7df9bf7ebb">

**Comment by drdhaval2785** [comment]
Thanks. I tried to grep whatever had 'abch' and add 'acph' to it, but this script somehow missed my attention.
