### ISSUE TITLE
Learning to follow the steps for ACPH and ACSJ

### ISSUE THREAD

**Issue by drdhaval2785** [funderburkjim/kosha-dev#25]
@funderburkjim has identified steps required to be followed for taking the changes made in this repository to CDSL in #23 .

I intend to do the shifting of Abhidhānachintāmaṇipariśiṣṭa (ACPH) and Abhidhānachintāmaṇiśiloñcha (ACSJ) myself as an exercise.

If I come across any lacuna in the documentation, I will try to correct ‌or seek help of Jim in this issue.
The present issue is a placeholder for this purpose.

**Comment by drdhaval2785** [comment]
Dropped this idea in favour of #26 
As all my koshas have the same format, the code which works for 'ABCH' will work with 'ACPH' and 'ACSJ' and all subsequent koshas.

**Comment by funderburkjim** [comment]
Good to know subsequent koshas can be handled similarly in the cologne 'framework'.
