### ISSUE TITLE
List view error 400

### ISSUE THREAD

**Issue by drdhaval2785** [funderburkjim/kosha-dev#3]
Leads to error 400

![Screenshot_2023-03-19_12-59-47](https://user-images.githubusercontent.com/5755132/226160537-d0a0d113-04fd-4651-afa9-d1690d2b31ae.png)

**Comment by funderburkjim** [comment]
This is related to the simple-search error mentioned at https://github.com/sanskrit-lexicon/MWS/issues/157

**Comment by funderburkjim** [comment]
400 message now absent.  See [commit](https://github.com/funderburkjim/kosha-dev/commit/036d5801a0ded9ba39adfb4762f78e1f5207afad)

**Comment by funderburkjim** [comment]
Of course the 'list' panel is still wrong.  That's another problem.

<img width="915" alt="image" src="https://user-images.githubusercontent.com/6393033/226696090-cd42c0b9-fcb0-47d4-b197-b305590e208e.png">
