### ISSUE TITLE
Allow access to push

### ISSUE THREAD

**Issue by drdhaval2785** [funderburkjim/kosha-dev#4]
@funderburkjim 
You will have to allow me access to push to make changes in this repository.

**Comment by funderburkjim** [comment]
I added you as a collaborator.   Can you push now?

**Comment by drdhaval2785** [comment]
Not able to push yet

**Comment by funderburkjim** [comment]
@drdhaval2785 The message said 'invite expired'.
I removed you, and then added you again as collaborator.
I see 'Awaiting drdhaval2785’s response'
You may need to accept the invitation.

If 'collaborator' process fails, maybe some other approach is needed ?  What do you suggest?

**Comment by drdhaval2785** [comment]
I accepted. Let me check tomorrow if the push works.

**Comment by funderburkjim** [comment]
You now show as Collaborator

**Comment by drdhaval2785** [comment]
Was able to push.
