### ISSUE TITLE
Title bar is erroneous

### ISSUE THREAD

**Issue by drdhaval2785** [funderburkjim/kosha-dev#9]
The title bar gives Abhidhānaratnamālā of Halāyudha.
Correct would be Anekārthanāmamālā of Harṣakīrti.

![Screenshot_2023-04-02_17-23-05](https://user-images.githubusercontent.com/5755132/229351160-82163ae2-fe41-43fc-a456-f6ee5d2aed1a.png)

**Comment by funderburkjim** [comment]
Corrected.

<img width="565" alt="image" src="https://user-images.githubusercontent.com/6393033/230699200-b2288390-8815-42e5-9876-fe968f76030c.png">
